In [1]:
import pandas as pd
import numpy as np
import os
import seaborn as sns
import plotly.express as px
from datetime import datetime as dt, timezone as tz

In [2]:
os.getcwd()

'C:\\Users\\Dell\\Documents\\KaggleDatasets\\SolarPowerPlant'

In [3]:
data_location = os.getcwd() + "\\archive\\"
filename_plant1_weather = "Plant_1_Weather_Sensor_Data.csv"
filename_plant1_generation = "Plant_1_Generation_Data.csv"
filename_plant2_generation = "Plant_2_Generation_Data.csv"
filename_plant2_weather = "Plant_2_Weather_Sensor_Data.csv"

In [5]:
plant1_generation_df = pd.read_csv(data_location + filename_plant1_generation)
plant2_generation_df = pd.read_csv(data_location + filename_plant2_generation)
plant2_weather_df = pd.read_csv(data_location + filename_plant2_weather)
plant1_weather_df = pd.read_csv(data_location + filename_plant1_weather)

In [6]:
plant1_generation_df["plant"] = "P_1"
plant2_generation_df["plant"] = "P_2"
plant1_weather_df["plant"] = "P_1"
plant2_weather_df["plant"] = "P_2"

In [7]:
generation_df = plant1_generation_df.append(plant2_generation_df)
weather_df = plant1_weather_df.append(plant2_weather_df)

In [8]:
generation_df.describe()

           PLANT_ID       DC_POWER       AC_POWER    DAILY_YIELD   TOTAL_YIELD
count  1.364760e+05  136476.000000  136476.000000  136476.000000  1.364760e+05
mean   4.135497e+06    1708.541497     274.803511    3295.433783  3.303821e+08
std    4.999862e+02    3222.181273     380.182569    3035.294425  6.085705e+08
min    4.135001e+06       0.000000       0.000000       0.000000  0.000000e+00
25%    4.135001e+06       0.000000       0.000000      28.321429  6.520020e+06
50%    4.135001e+06       6.050000       3.506905    2834.803572  7.269333e+06
75%    4.136001e+06    1155.788333     532.673333    5992.000000  2.826096e+08
max    4.136001e+06   14471.125000    1410.950000    9873.000000  2.247916e+09

In [131]:
weather_df.describe()

           PLANT_ID  AMBIENT_TEMPERATURE  MODULE_TEMPERATURE  IRRADIATION
count  6.441000e+03          6441.000000         6441.000000  6441.000000
mean   4.135507e+06            26.815672           31.941762     0.230551
std    5.000031e+02             3.938901           11.835033     0.306877
min    4.135001e+06            20.398505           18.140415     0.000000
25%    4.135001e+06            23.662696           22.429024     0.000000
50%    4.136001e+06            25.954460           26.394380     0.022282
75%    4.136001e+06            29.355584           40.821388     0.443340
max    4.136001e+06            39.181638           66.635953     1.221652

In [9]:
generation_df.head()

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,plant
0,15-05-2020 00:00,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6259559.0,P_1
1,15-05-2020 00:00,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6183645.0,P_1
2,15-05-2020 00:00,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6987759.0,P_1
3,15-05-2020 00:00,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7602960.0,P_1
4,15-05-2020 00:00,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7158964.0,P_1

In [10]:
generation_df.tail()

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,plant
67693,2020-06-17 23:45:00,4136001,q49J1IKaHRwDQnt,0.0,0.0,4157.0,520758.0,P_2
67694,2020-06-17 23:45:00,4136001,rrq4fwE8jgrTyWY,0.0,0.0,3931.0,121131356.0,P_2
67695,2020-06-17 23:45:00,4136001,vOuJvMaM2sgwLmb,0.0,0.0,4322.0,2427691.0,P_2
67696,2020-06-17 23:45:00,4136001,xMbIugepa2P7lBB,0.0,0.0,4218.0,106896394.0,P_2
67697,2020-06-17 23:45:00,4136001,xoJJ8DcxJEcupym,0.0,0.0,4316.0,209335741.0,P_2

In [11]:
weather_df.head()

,DATE_TIME,PLANT_ID,SOURCE_KEY,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION,plant
0,2020-05-15 00:00:00,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,P_1
1,2020-05-15 00:15:00,4135001,HmiyD2TTLFNqkNe,25.084589,22.761668,0.0,P_1
2,2020-05-15 00:30:00,4135001,HmiyD2TTLFNqkNe,24.935753,22.592306,0.0,P_1
3,2020-05-15 00:45:00,4135001,HmiyD2TTLFNqkNe,24.846130,22.360852,0.0,P_1
4,2020-05-15 01:00:00,4135001,HmiyD2TTLFNqkNe,24.621525,22.165423,0.0,P_1

In [12]:
weather_df.tail()

,DATE_TIME,PLANT_ID,SOURCE_KEY,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION,plant
3254,2020-06-17 22:45:00,4136001,iq8k7ZNt4Mwm3w0,23.511703,22.856201,0.0,P_2
3255,2020-06-17 23:00:00,4136001,iq8k7ZNt4Mwm3w0,23.482282,22.744190,0.0,P_2
3256,2020-06-17 23:15:00,4136001,iq8k7ZNt4Mwm3w0,23.354743,22.492245,0.0,P_2
3257,2020-06-17 23:30:00,4136001,iq8k7ZNt4Mwm3w0,23.291048,22.373909,0.0,P_2
3258,2020-06-17 23:45:00,4136001,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2

In [13]:
generation_df.loc[generation_df["plant"] == "P_1","DATE_TIME"] = \
    pd.to_datetime(generation_df[generation_df["plant"] == "P_1"].DATE_TIME, format="%d-%m-%Y %H:%M")
generation_df.loc[generation_df["plant"] == "P_2","DATE_TIME"] = \
    pd.to_datetime(generation_df[generation_df["plant"] == "P_2"].DATE_TIME)

In [14]:
generation_df["DATE_TIME"] = \
    generation_df.DATE_TIME.apply(
        lambda x: dt.fromtimestamp(x/1000000000).astimezone(tz.utc).strftime("%Y-%m-%d %H:%M:%S")
)

In [15]:
generation_df[(generation_df["plant"] == "P_1")].tail()

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,plant
68773,2020-06-17 23:45:00,4135001,uHbuxQJl8lW7ozc,0.0,0.0,5967.000,7287002.0,P_1
68774,2020-06-17 23:45:00,4135001,wCURE6d3bPkepu2,0.0,0.0,5147.625,7028601.0,P_1
68775,2020-06-17 23:45:00,4135001,z9Y9gH1T5YWrNuG,0.0,0.0,5819.000,7251204.0,P_1
68776,2020-06-17 23:45:00,4135001,zBIq5rxdHJRwDNY,0.0,0.0,5817.000,6583369.0,P_1
68777,2020-06-17 23:45:00,4135001,zVJPv84UY57bAof,0.0,0.0,5910.000,7363272.0,P_1

In [16]:
generation_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 136476 entries, 0 to 67697
Data columns (total 8 columns):
DATE_TIME      136476 non-null object
PLANT_ID       136476 non-null int64
SOURCE_KEY     136476 non-null object
DC_POWER       136476 non-null float64
AC_POWER       136476 non-null float64
DAILY_YIELD    136476 non-null float64
TOTAL_YIELD    136476 non-null float64
plant          136476 non-null object
dtypes: float64(4), int64(1), object(3)
memory usage: 9.4+ MB

In [17]:
weather_df.DATE_TIME = pd.to_datetime(weather_df.DATE_TIME)
generation_df.DATE_TIME = pd.to_datetime(generation_df.DATE_TIME)

In [18]:
generation_df.tail()

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,plant
67693,2020-06-17 23:45:00,4136001,q49J1IKaHRwDQnt,0.0,0.0,4157.0,520758.0,P_2
67694,2020-06-17 23:45:00,4136001,rrq4fwE8jgrTyWY,0.0,0.0,3931.0,121131356.0,P_2
67695,2020-06-17 23:45:00,4136001,vOuJvMaM2sgwLmb,0.0,0.0,4322.0,2427691.0,P_2
67696,2020-06-17 23:45:00,4136001,xMbIugepa2P7lBB,0.0,0.0,4218.0,106896394.0,P_2
67697,2020-06-17 23:45:00,4136001,xoJJ8DcxJEcupym,0.0,0.0,4316.0,209335741.0,P_2

In [19]:
weather_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6441 entries, 0 to 3258
Data columns (total 7 columns):
DATE_TIME              6441 non-null datetime64[ns]
PLANT_ID               6441 non-null int64
SOURCE_KEY             6441 non-null object
AMBIENT_TEMPERATURE    6441 non-null float64
MODULE_TEMPERATURE     6441 non-null float64
IRRADIATION            6441 non-null float64
plant                  6441 non-null object
dtypes: datetime64[ns](1), float64(3), int64(1), object(2)
memory usage: 402.6+ KB

In [20]:
generation_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 136476 entries, 0 to 67697
Data columns (total 8 columns):
DATE_TIME      136476 non-null datetime64[ns]
PLANT_ID       136476 non-null int64
SOURCE_KEY     136476 non-null object
DC_POWER       136476 non-null float64
AC_POWER       136476 non-null float64
DAILY_YIELD    136476 non-null float64
TOTAL_YIELD    136476 non-null float64
plant          136476 non-null object
dtypes: datetime64[ns](1), float64(4), int64(1), object(2)
memory usage: 9.4+ MB

In [21]:
del plant1_generation_df 
del plant2_generation_df 
del plant1_weather_df 
del plant2_weather_df

In [22]:
generation_df.to_csv("generation_df.csv")
weather_df.to_csv("weather_df.csv")

In [23]:
generation_df.PLANT_ID.unique()

array([4135001, 4136001], dtype=int64)

In [24]:
generation_df.shape

(136476, 8)

In [25]:
weather_df.PLANT_ID.unique()

array([4135001, 4136001], dtype=int64)

In [26]:
consolidated_df = generation_df.merge(weather_df, how='left', on=["DATE_TIME", "PLANT_ID"])

In [27]:
consolidated_df.shape

(136476, 13)

In [28]:
consolidated_df["DATE"] = consolidated_df.DATE_TIME.apply(lambda x: x.date())

In [29]:
consolidated_df["TIME"] = consolidated_df.DATE_TIME.apply(lambda x: x.time())

In [35]:
consolidated_df.tail()

,DATE_TIME,PLANT_ID,SOURCE_KEY_x,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,plant_x,SOURCE_KEY_y,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION,plant_y,DATE,TIME
136471,2020-06-17 23:45:00,4136001,q49J1IKaHRwDQnt,0.0,0.0,4157.0,520758.0,P_2,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2,2020-06-17,23:45:00
136472,2020-06-17 23:45:00,4136001,rrq4fwE8jgrTyWY,0.0,0.0,3931.0,121131356.0,P_2,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2,2020-06-17,23:45:00
136473,2020-06-17 23:45:00,4136001,vOuJvMaM2sgwLmb,0.0,0.0,4322.0,2427691.0,P_2,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2,2020-06-17,23:45:00
136474,2020-06-17 23:45:00,4136001,xMbIugepa2P7lBB,0.0,0.0,4218.0,106896394.0,P_2,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2,2020-06-17,23:45:00
136475,2020-06-17 23:45:00,4136001,xoJJ8DcxJEcupym,0.0,0.0,4316.0,209335741.0,P_2,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2,2020-06-17,23:45:00

In [47]:
consolitdatd_df = consolidated_df.sort_values(["DATE", "TIME"]).reset_index()

In [49]:
consolidated_df

,DATE_TIME,PLANT_ID,SOURCE_KEY_x,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,plant_x,SOURCE_KEY_y,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION,plant_y,DATE,TIME
0,2020-05-15 00:00:00,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6.259559e+06,P_1,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,P_1,2020-05-15,00:00:00
1,2020-05-15 00:00:00,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6.183645e+06,P_1,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,P_1,2020-05-15,00:00:00
2,2020-05-15 00:00:00,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6.987759e+06,P_1,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,P_1,2020-05-15,00:00:00
3,2020-05-15 00:00:00,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7.602960e+06,P_1,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,P_1,2020-05-15,00:00:00
4,2020-05-15 00:00:00,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7.158964e+06,P_1,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,P_1,2020-05-15,00:00:00
5,2020-05-15 00:00:00,4135001,VHMLBKoKgIrUVDU,0.0,0.0,0.0,7.206408e+06,P_1,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,P_1,2020-05-15,00:00:00
6,2020-05-15 00:00:00,4135001,WRmjgnKYAwPKWDb,0.0,0.0,0.0,7.028673e+06,P_1,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,P_1,2020-05-15,00:00:00
7,2020-05-15 00:00:00,4135001,ZnxXDlPa8U1GXgE,0.0,0.0,0.0,6.522172e+06,P_1,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,P_1,2020-05-15,00:00:00
8,2020-05-15 00:00:00,4135001,ZoEaEvLYb1n2sOq,0.0,0.0,0.0,7.098099e+06,P_1,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,P_1,2020-05-15,00:00:00
9,2020-05-15 00:00:00,4135001,adLQvlD726eNBSB,0.0,0.0,0.0,6.271355e+06,P_1,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,P_1,2020-05-15,00:00:00
10,2020-05-15 00:00:00,4135001,bvBOhCH3iADSZry,0.0,0.0,0.0,6.316803e+06,P_1,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,P_1,2020-05-15,00:00:00
11,2020-05-15 00:00:00,4135001,iCRJl6heRkivqQ3,0.0,0.0,0.0,7.177992e+06,P_1,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,P_1,2020-05-15,00:00:00
12,2020-05-15 00:00:00,4135001,ih0vzX44oOqAx2f,0.0,0.0,0.0,6.185184e+06,P_1,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,P_1,2020-05-15,00:00:00
13,2020-05-15 00:00:00,4135001,pkci93gMrogZuBj,0.0,0.0,0.0,7.169102e+06,P_1,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,P_1,2020-05-15,00:00:00
14,2020-05-15 00:00:00,4135001,rGa61gmuvPhdLxV,0.0,0.0,0.0,7.111493e+06,P_1,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,P_1,2020-05-15,00:00:00
15,2020-05-15 00:00:00,4135001,sjndEbLyjtCKgGv,0.0,0.0,0.0,7.016832e+06,P_1,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,P_1,2020-05-15,00:00:00
16,2020-05-15 00:00:00,4135001,uHbuxQJl8lW7ozc,0.0,0.0,0.0,7.038681e+06,P_1,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,P_1,2020-05-15,00:00:00
17,2020-05-15 00:00:00,4135001,wCURE6d3bPkepu2,0.0,0.0,0.0,6.782598e+06,P_1,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,P_1,2020-05-15,00:00:00
18,2020-05-15 00:00:00,4135001,z9Y9gH1T5YWrNuG,0.0,0.0,0.0,7.007866e+06,P_1,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,P_1,2020-05-15,00:00:00
19,2020-05-15 00:00:00,4135001,zBIq5rxdHJRwDNY,0.0,0.0,0.0,6.339380e+06,P_1,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,P_1,2020-05-15,00:00:00
20,2020-05-15 00:00:00,4135001,zVJPv84UY57bAof,0.0,0.0,0.0,7.116151e+06,P_1,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0,P_1,2020-05-15,00:00:00
21,2020-05-15 00:15:00,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6.259559e+06,P_1,HmiyD2TTLFNqkNe,25.084589,22.761668,0.0,P_1,2020-05-15,00:15:00
22,2020-05-15 00:15:00,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6.183645e+06,P_1,HmiyD2TTLFNqkNe,25.084589,22.761668,0.0,P_1,2020-05-15,00:15:00
23,2020-05-15 00:15:00,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6.987759e+06,P_1,HmiyD2TTLFNqkNe,25.084589,22.761668,0.0,P_1,2020-05-15,00:15:00
24,2020-05-15 00:15:00,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7.602960e+06,P_1,HmiyD2TTLFNqkNe,25.084589,22.761668,0.0,P_1,2020-05-15,00:15:00
25,2020-05-15 00:15:00,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7.158964e+06,P_1,HmiyD2TTLFNqkNe,25.084589,22.761668,0.0,P_1,2020-05-15,00:15:00
26,2020-05-15 00:15:00,4135001,VHMLBKoKgIrUVDU,0.0,0.0,0.0,7.206408e+06,P_1,HmiyD2TTLFNqkNe,25.084589,22.761668,0.0,P_1,2020-05-15,00:15:00
27,2020-05-15 00:15:00,4135001,WRmjgnKYAwPKWDb,0.0,0.0,0.0,7.028673e+06,P_1,HmiyD2TTLFNqkNe,25.084589,22.761668,0.0,P_1,2020-05-15,00:15:00
28,2020-05-15 00:15:00,4135001,ZnxXDlPa8U1GXgE,0.0,0.0,0.0,6.522172e+06,P_1,HmiyD2TTLFNqkNe,25.084589,22.761668,0.0,P_1,2020-05-15,00:15:00
29,2020-05-15 00:15:00,4135001,ZoEaEvLYb1n2sOq,0.0,0.0,0.0,7.098099e+06,P_1,HmiyD2TTLFNqkNe,25.084589,22.761668,0.0,P_1,2020-05-15,00:15:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136446,2020-06-17 23:30:00,4136001,mqwcsP2rE7J0TFp,0.0,0.0,4238.0,5.938150e+08,P_2,iq8k7ZNt4Mwm3w0,23.291048,22.373909,0.0,P_2,2020-06-17,23:30:00
136447,2020-06-17 23:30:00,4136001,oZ35aAeoifZaQzV,0.0,0.0,4467.0,1.660189e+09,P_2,iq8k7ZNt4Mwm3w0,23.291048,22.373909,0.0,P_2,2020-06-17,23:30:00
136448,2020-06-17 23:30:00,4136001,oZZkBaNadn6DNKz,0.0,0.0,4389.0,1.708288e+09,P_2,iq8k7ZNt4Mwm3w0,23.291048,22.373909,0.0,P_2,2020-06-17,23:30:00
136449,2020-06-17 23:30:00,4136001,q49J1IKaHRwDQnt,0.0,0.0,4157.0,5.207580e+05,P_2,iq8k7ZNt4Mwm3w0,23.291048,22.373909,0.0,P_2,2020-06-17,23:30:00
136450,2020-06-17 23:30:00,4136001,rrq4fwE8jgrTyWY,0.0,0.0,3931.0,1.211314e+08,P_2,iq8k7ZNt4Mwm3w0,23.291048,22.373909,0.0,P_2,2020-06-17,23:30:00
136451,2020-06-17 23:30:00,4136001,vOuJvMaM2sgwLmb,0.0,0.0,4322.0,2.427691e+06,P_2,iq8k7ZNt4Mwm3w0,23.291048,22.373909,0.0,P_2,2020-06-17,23:30:00
136452,2020-06-17 23:30:00,4136001,xMbIugepa2P7lBB,0.0,0.0,4218.0,1.068964e+08,P_2,iq8k7ZNt4Mwm3w0,23.291048,22.373909,0.0,P_2,2020-06-17,23:30:00
136453,2020-06-17 23:30:00,4136001,xoJJ8DcxJEcupym,0.0,0.0,4316.0,2.093357e+08,P_2,iq8k7ZNt4Mwm3w0,23.291048,22.373909,0.0,P_2,2020-06-17,23:30:00
136454,2020-06-17 23:45:00,4136001,4UPUqMRk7TRMgml,0.0,0.0,4446.0,2.653495e+06,P_2,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2,2020-06-17,23:45:00
136455,2020-06-17 23:45:00,4136001,81aHJ1q11NBPMrL,0.0,0.0,4306.0,1.215486e+09,P_2,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2,2020-06-17,23:45:00
136456,2020-06-17 23:45:00,4136001,9kRcWv60rDACzjR,0.0,0.0,4197.0,2.247916e+09,P_2,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2,2020-06-17,23:45:00
136457,2020-06-17 23:45:00,4136001,Et9kgGMDl729KT4,0.0,0.0,4020.0,1.854162e+06,P_2,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2,2020-06-17,23:45:00
136458,2020-06-17 23:45:00,4136001,IQ2d7wF4YD8zU1Q,0.0,0.0,4251.0,2.018506e+07,P_2,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2,2020-06-17,23:45:00
136459,2020-06-17 23:45:00,4136001,LYwnQax7tkwH5Cb,0.0,0.0,3968.0,1.795116e+09,P_2,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2,2020-06-17,23:45:00
136460,2020-06-17 23:45:00,4136001,LlT2YUhhzqhg5Sw,0.0,0.0,4121.0,2.827890e+08,P_2,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2,2020-06-17,23:45:00
136461,2020-06-17 23:45:00,4136001,Mx2yZCDsyf6DPfv,0.0,0.0,4441.0,2.683351e+06,P_2,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2,2020-06-17,23:45:00
136462,2020-06-17 23:45:00,4136001,NgDl19wMapZy17u,0.0,0.0,4239.0,1.117460e+08,P_2,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2,2020-06-17,23:45:00
136463,2020-06-17 23:45:00,4136001,PeE6FRyGXUgsRhN,0.0,0.0,4258.0,1.348549e+09,P_2,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2,2020-06-17,23:45:00
136464,2020-06-17 23:45:00,4136001,Qf4GUc1pJu5T6c6,0.0,0.0,4398.0,8.386467e+08,P_2,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2,2020-06-17,23:45:00
136465,2020-06-17 23:45:00,4136001,Quc1TzYxW2pYoWX,0.0,0.0,3702.0,3.296459e+08,P_2,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2,2020-06-17,23:45:00
136466,2020-06-17 23:45:00,4136001,V94E5Ben1TlhnDV,0.0,0.0,4324.0,1.412293e+09,P_2,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2,2020-06-17,23:45:00
136467,2020-06-17 23:45:00,4136001,WcxssY2VbP4hApt,0.0,0.0,4331.0,1.819119e+08,P_2,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2,2020-06-17,23:45:00
136468,2020-06-17 23:45:00,4136001,mqwcsP2rE7J0TFp,0.0,0.0,4238.0,5.938150e+08,P_2,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2,2020-06-17,23:45:00
136469,2020-06-17 23:45:00,4136001,oZ35aAeoifZaQzV,0.0,0.0,4467.0,1.660189e+09,P_2,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2,2020-06-17,23:45:00
136470,2020-06-17 23:45:00,4136001,oZZkBaNadn6DNKz,0.0,0.0,4389.0,1.708288e+09,P_2,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2,2020-06-17,23:45:00
136471,2020-06-17 23:45:00,4136001,q49J1IKaHRwDQnt,0.0,0.0,4157.0,5.207580e+05,P_2,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2,2020-06-17,23:45:00
136472,2020-06-17 23:45:00,4136001,rrq4fwE8jgrTyWY,0.0,0.0,3931.0,1.211314e+08,P_2,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2,2020-06-17,23:45:00
136473,2020-06-17 23:45:00,4136001,vOuJvMaM2sgwLmb,0.0,0.0,4322.0,2.427691e+06,P_2,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2,2020-06-17,23:45:00
136474,2020-06-17 23:45:00,4136001,xMbIugepa2P7lBB,0.0,0.0,4218.0,1.068964e+08,P_2,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2,2020-06-17,23:45:00
136475,2020-06-17 23:45:00,4136001,xoJJ8DcxJEcupym,0.0,0.0,4316.0,2.093357e+08,P_2,iq8k7ZNt4Mwm3w0,23.202871,22.535908,0.0,P_2,2020-06-17,23:45:00

In [50]:
px.line(x="TIME", y="DAILY_YIELD", line_group="DATE", data_frame=consolidated_df[["TIME", "DAILY_YIELD", "DATE"]])

KeyError: ('', '', '', '', '', Timestamp('2020-05-15 00:00:00'))

In [39]:
weather_df.SOURCE_KEY.unique()

array(['HmiyD2TTLFNqkNe', 'iq8k7ZNt4Mwm3w0'], dtype=object)